const summerCollection = [
    {
      id: 0,
      imgSrc: "./img/products/air force/shoes1.webp",
      brand: "Nike Sportswear",
      name: "AIR FORCE 1 07 - Trainers",
      inStock: 5,
      price: 89,
    },
    {
      id: 1,
      imgSrc: "./img/products/jeans/straight leg jeans.webp",
      brand: "Mustang",
      name: "BIG SUR - Straight leg jeans",
      price: 90,
      inStock: 7,
    },
    {
      id: 2,
      imgSrc: "./img/products/shirt/short sleeve - Shirt.webp",
      brand: "PULL&BEAR",
      name: "JOIN LIFE - Basic T-shirt",
      inStock: 8,
      price: 99,
    },
    {
      id: 3,
      imgSrc: "./img/products/shoos/lacosta1.webp",
      brand: "Lacoste",
      name: "T-CLIPS -Modern Trainers",
      inStock: 10,
      price: 90,
    },
    {
      id: 4,
      imgSrc: "./img/products/sportswear/1.webp",
      brand: "Nike Sportswear",
      name: "CLUB - Tracksuit bottoms",
      inStock: 20,
      price: 50,
    },      
    {
      id: 5,
      imgSrc: "./img/products/t-shirts/black.webp" ,
      brand: "Bershka",
      name: "Basic T-shirt",
      inStock: 10,
      price: 30,
    },
    {
      id: 6,
      imgSrc: "./img/products/Tracksuit bottoms/Tracksuit bottoms.webp" ,
      brand: "Urban Classics",
      name: "Tracksuit bottoms",
      inStock: 10,
      price: 100,
    },
    {
      id: 7,
      imgSrc: "./img/products/ZIP HOODY/sweater.webp" ,
      brand: "ZIP HOODY - Zip-up sweatshirt",
      name: "Zip-up sweatshirt",
      inStock: 10,
      price: 110,
    },
    
];

const allProducts=[
    {
        id: 0,
        category:"shoes",
        imgSrc: "./img/products/air force/shoes1.webp",
        brand: "Nike Sportswear",
        name: "AIR FORCE 1 07 - Trainers",
        inStock: 5,
        price: 89,
      },
      {
        id: 1,
        imgSrc: "./img/products/jeans/straight leg jeans.webp",
        brand: "Mustang",
        name: "BIG SUR - Straight leg jeans",
        price: 90,
        inStock: 7,
      },
      {
        id: 2,
        category:"shirt",
        imgSrc: "./img/products/shirt/short sleeve - Shirt.webp",
        brand: "PULL&BEAR",
        name: "JOIN LIFE - Basic T-shirt",
        inStock: 8,
        price: 99,
      },
      {
        id: 3,
        category:"shoes",
        imgSrc: "./img/products/shoos/lacosta1.webp",
        brand: "Lacoste",
        name: "T-CLIPS -Modern Trainers",
        inStock: 10,
        price: 90,
      },
      {
        id: 4,
        category:"sweatpants",
        imgSrc: "./img/products/sportswear/1.webp",
        brand: "Nike Sportswear",
        name: "CLUB - Tracksuit bottoms",
        inStock: 20,
        price: 50,
      },      
      {
        id: 5,
        category:"shirt",
        imgSrc: "./img/products/t-shirts/black.webp" ,
        brand: "Bershka",
        name: "Basic T-shirt",
        inStock: 10,
        price: 30,
      },
      {
        id: 6,
        category:"sweatpants",
        imgSrc: "./img/products/Tracksuit bottoms/Tracksuit bottoms.webp" ,
        brand: "Urban Classics",
        name: "Tracksuit bottoms",
        inStock: 10,
        price: 100,
      },
      {
        id: 7,
        category:"hoody",
        imgSrc: "./img/products/ZIP HOODY/sweater.webp" ,
        brand: "ZIP HOODY - Zip-up sweatshirt",
        name: "Zip-up sweatshirt",
        inStock: 10,
        price: 110,
      },
    {
        id: 8,
        category:"shirt",
        imgSrc: "./img/products/format shirts/format shirt.webp" ,
        brand: "HUGO",
        name: "JASON SLIM FIT - Formal shirt",
        inStock: 10,
        price: 55,
      },
      {
        id: 9,
        category:"jaket",
        imgSrc: "./img/products/jakets/jakets.webp" ,
        brand: "Nike Sportswear",
        name: "Windbreaker",
        inStock: 10,
        price: 90,
      },
      {
        id: 10,
        category:"shirt",
        imgSrc: "./img/products/top/top.webp" ,
        brand: "JP1880",
        name: "BIG TALL HENLEY - Long sleeved top",
        inStock: 50,
        price: 20,
      },
      {
        id: 11,
        category:"jaket",
        imgSrc: "./img/products/light-jacket/ljacket.webp" ,
        brand: "Threadbare",
        name: "LUXE - Light jacket",
        inStock: 50,
        price: 80,
      },
]

const detailProducts=[
    {
        id:0,
        imgSrcBig:"./img/products/air force/shoes1.webp",
        imgSrc2:"./img/products/air force/shoes2.webp",
        imgSrc3:"./img/products/air force/shoes3.webp",
        imgSrc4:"./img/products/air force/shoes4.webp",
        name:"Men's fashion trainers",
        price:"89",
        details:"Air Force Ones are high-quality leather shoes that occasionally use synthetic leather. And since Nike must live up to the reputation and price charged for its high-end shoes, using genuine leather is  natural.Air Force Ones are made of a combination of leather and rubber1. Some parts of the shoe also include suede, canvas, and other different materials1. The shoes are typically made of EVA  foam, lightweight plastic and mesh fabrics2. The Nike Air technology makes the soles of these shoes flexible, durable, and elastic3. The original high-top Air Force 1 is intended for intense sport and the grip of the concentric circle outsole makes them perfect for use on the court3."
    },
    {
        id:1,
        imgSrcBig:"./img/products/jeans/straight leg jeans.webp",
        imgSrc2:"./img/products/jeans/straight leg jeans2.webp",
        imgSrc3:"./img/products/jeans/straight leg jeans3.webp",
        imgSrc4:"./img/products/jeans/straight leg jeans4.webp",
        name:"BIG SUR - Straight leg jeans",
        price:"90",
        details:"Straight leg jeans are denim pants that are cut so that the diameter of the leg opening is almost exactly the same from the knee down to the ankle. They differ from flare jeans and that begin to widen at the middle of the calf and bell bottoms that begin to widen at the knee."
    },
    {
        id:2,
        imgSrcBig:"./img/products/shirt/short sleeve - Shirt.webp",
        imgSrc2:"./img/products/shirt/shirt2.webp",
        imgSrc3:"./img/products/shirt/shirt3.webp",
        imgSrc4:"./img/products/shirt/shirt4.webp",
        name:"JOIN LIFE - Basic T-shirt",
        price:"99",
        details:"A T-shirt (also spelled tee shirt), or tee for short, is a style of fabric shirt named after the T shape of its body and sleeves. Traditionally, it has short sleeves and a round neckline, known as a crew neck, which lacks a collar. T-shirts are generally made of a stretchy, light, and inexpensive fabric and are easy to clean. The T-shirt evolved from undergarments used in the 19th century and, in the mid-20th century, transitioned from undergarment to general-use casual clothing."
    },
    {
        id:3,
        imgSrcBig:"./img/products/shoos/lacosta1.webp",
        imgSrc2:"./img/products/shoos/lacosta2.webp",
        imgSrc3:"./img/products/shoos/lacosta3.webp",
        imgSrc4:"./img/products/shoos/lacosta4.webp",
        name:"T-CLIPS -Modern Trainers",
        price:"90",
        details:"A new modern classic: the T-Clip. 80s detailing. Vintage silhouette. Blended with modern flair.  Leather, synthetic and textile uppers:  Soft and premium leather designed in natural hues."
      },
    {
      id:4,
      imgSrcBig:"./img/products/sportswear/1.webp",
      imgSrc2:"./img/products/sportswear/2.webp",
      imgSrc3:"./img/products/sportswear/3.webp",
      imgSrc4:"./img/products/sportswear/4.webp",
      name:"CLUB - Tracksuit bottoms",
      price:"50",
      details:"Nike offers an array of tracksuit bottoms that move with you—whatever the activity, whether it's breaking a sweat or sitting courtside at a basketball game. If you're in the market for comfortable, long-lasting choices, you've come to the right place. This round-up of Nike tracksuit bottoms for men ticks all the boxes."
    },
    {
      id:5,
      imgSrcBig:"./img/products/t-shirts/black.webp",
      imgSrc2:"./img/products/t-shirts/brown.webp",
      imgSrc3:"./img/products/t-shirts/violet.webp",
      imgSrc4:"./img/products/t-shirts/white4.webp",
      name:"Basic T-shirt",
      price:"30",
      details:"Caring for your garments is a way to extend their useful life. Follow the care instructions and only wash your garments when necessary. Washing and drying our garments less often extends their lives and reduces water and energy use."
  },
  {
    id:6,
    imgSrcBig:"./img/products/Tracksuit bottoms/Tracksuit bottoms.webp",
    imgSrc2:"./img/products/Tracksuit bottoms/Tracksuit bottoms2.webp",
    imgSrc3:"./img/products/Tracksuit bottoms/Tracksuit bottoms3.webp",
    imgSrc4:"./img/products/Tracksuit bottoms/Tracksuit bottoms4.webp",
    name:"Tracksuit bottoms",
    price:"100",
    details:"Nike offers an array of tracksuit bottoms that move with you—whatever the activity, whether it's breaking a sweat or sitting courtside at a basketball game. If you're in the market for comfortable, long-lasting choices, you've come to the right place. This round-up of Nike tracksuit bottoms for men ticks all the boxes."
},
{
  id:7,
  imgSrcBig:"./img/products/ZIP HOODY/sweater.webp",
  imgSrc2:"./img/products/ZIP HOODY/sweater2.webp",
  imgSrc3:"./img/products/ZIP HOODY/sweater3.webp",
  imgSrc4:"./img/products/ZIP HOODY/sweater4.webp",
  name:"Zip-up sweatshirt",
  price:"110",
  details:"A hoodie  is a sweatshirt with a hood. Hoodies with zippers usually include two pockets on the lower front, one on either side of the zipper, while pullover hoodies (without zippers) often include a single large muff or pocket in the same location."
},
{
  id:8,
  imgSrcBig:"./img/products/format shirts/format shirt.webp",
  imgSrc2:"./img/products/format shirts/formatshirt2.webp",
  imgSrc3:"./img/products/format shirts/formatshirt3.webp",
  imgSrc4:"./img/products/format shirts/formatimage4.webp",
  name:"JASON SLIM FIT - Formal shirt",
  price:"55",
  details:"A formal shirt  otherwise known as the dress shirt  can be identified by its stiff collar, lustrous fabric, long tails and single or double cuffs. Although patterned versions are available, the most popular styles come in conservative colours such as white, blue or pink."
},
{
  id:9,
  imgSrcBig:"./img/products/jakets/jakets.webp",
  imgSrc2:"./img/products/jakets/jakets2.webp",
  imgSrc3:"./img/products/jakets/jakets3.webp",
  imgSrc4:"./img/products/jakets/jakets4.webp",
  name:"Windbreaker",
  price:"90",
  details:"Cotton: A natural fiber that is fluffy, soft, a great insulator, and can be dyed in many different colors. Cotton is not waterproof and does not offer good protection from the wind."
},
{
  id:10,
  imgSrcBig:"./img/products/top/top.webp",
  imgSrc2:"./img/products/top/top2.webp",
  imgSrc3:"./img/products/top/top3webp.webp",
  imgSrc4:"./img/products/top/top4.webp",
  name:"BIG TALL HENLEY - Long sleeved top",
  price:"20",
  details:"T-shirt  also tee shirt, a casual shirt without a collar or buttons, made of a stretchy, finely knit fabric, usually cotton, and usually short-sleeved. Originally worn under other shirts, it is now a common shirt for everyday wear in some countries. Long-sleeved T-shirt – a T-shirt with long sleeves that extend to cover the arms."
},
{
  id:11,
  imgSrcBig:"./img/products/light-jacket/ljaket.webp",
  imgSrc2:"./img/products/light-jacket/jak2.webp",
  imgSrc3:"./img/products/light-jacket/jak3.webp",
  imgSrc4:"./img/products/light-jacket/jak4.webp",
  name:"LUXE - Light jacket",
  price:"80",
  details:"Cotton: A natural fiber that is fluffy, soft, a great insulator, and can be dyed in many different colors. Cotton is not waterproof and does not offer good protection from the wind."
},
]